#server:
#  port: ${PORT:5000}
#security:
#  user:
#    password: ${eureka.password}
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
#  password: ${EUREKA_USER_PASSWORD:password}

  
server:
  port: 8761
  
  
  eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

  