server:
  port: ${PORT:5000}
security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}

  
#server:
#  port: ${PORT:8761}
#  security:
#  user:
#    password: ${eureka.password}
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#
#password: ${EUREKA_USER_PASSWORD:1234}
 

  